### ISSUE TITLE
Couldn't get the `DirectusSchema` global working in a pnpm workspace

### ISSUE THREAD

**Issue by Vincent-HD** [becem-gharbi/nuxt-directus#75] opened 2024-02-21 02:08 UTC
Hi, 
I can't get to work the DirectusSchema interface augmentation through `d.ts`. But without `pnpm workspace` it works great.

My current workspace is:
```
- apps
  - directus
  - frontend
    - types/global.d.ts
    - tsconfig.ts
- libs
  - now empty
```

Inside the `global.d.ts` I have the exact same code as the documentation in the readme
Inside the `tsconfig` I properly added the type roots to the correct folder.

BUT `readItems` Function for example is typed as `readItems<object>` since it can't seem to find the global schema declared in `global.d.ts`, and it defaults it at `object`.

What I also noticed is that `pnpm` seems to hoist the SDK in the root workspace `node_module` folder via symlink, and nuxt auto import it but not from the symlink but from root `../../../../node_modules/.pnpm/...`. I'm wondering if it's what is causing the issue, and the SDK can't find the Schema because of the hoisting.

Does it makes sense ?
I'm not sure at all though

**Comment by becem-gharbi** [comment] 2024-02-21 07:37
Hi, 
To be honest I'm not familiar with pnpm workspace. Nevertheless I have few notes that might help:
- Add `export{}` in the declaration file to ensure type augmentation.
- No need to modify `tsconfig.ts` as declaration files are automatically included in Nuxt.
- Try to create a global type to test if it's available in your app.

**Comment by Vincent-HD** [comment] 2024-02-21 09:22
Hmm, well I'm not familiar too ...

I was on my phone when I opened this issue, so there is more info:

global type:
```typescript
// apps/front/type/global.d.ts
import { CustomDirectusTypes } from './directusTypes';

type DirectusTypes =
	| 'directus_activity'
	| 'directus_collections'
	| 'directus_dashboards'
	| 'directus_fields'
	| 'directus_files'
	| 'directus_flows'
	| 'directus_folders'
	| 'directus_migrations'
	| 'directus_notifications'
	| 'directus_operations'
	| 'directus_panels'
	| 'directus_permissions'
	| 'directus_presets'
	| 'directus_relations'
	| 'directus_revisions'
	| 'directus_roles'
	| 'directus_sessions'
	| 'directus_settings'
	| 'directus_shares'
	| 'directus_translations'
	| 'directus_webhooks';

declare global {
	interface DirectusSchema extends Omit<CustomDirectusTypes, DirectusTypes> {}
}

export {};
```

I removed the tsconfig entry as you said.

I noticed something tho, it seems that I some point it correctly retrieve the correct type
![image](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/a276ee2c-b096-4840-80c2-963c2f5e424c)

![image](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/45dd06d0-5a4f-4e5b-ac89-032fb21ed599)

The hoisted import from pnpm in the generated `.nuxt/types/import.d.ts`:
![image](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/dce03b33-4897-427b-ae54-41c53f5820f7)

(it also seems to not using the SDK provided by the your package deps, but instead it's reusing the SDK installed by directus folder `apps/directus/<versionned directus>` as it would've import from ...@bg-dev/nuxt-directus... at some point right ?)

**Comment by becem-gharbi** [comment] 2024-02-21 09:53
> I noticed something tho, it seems that I some point it correctly retrieve the correct type

In order to make sure that the issue is in fact related to this module, try to:
- Remove `.nuxt` folder.
- Re-run the application.
- Restart your IDE.
- Check if `DirectusSchema` interface is globally available.

**Comment by Vincent-HD** [comment] 2024-02-21 15:25
Yep I already tried it.

But I think I got it, but I don't know how to solve it (I may have an idea)

I created a repo with two branch:
- one with two packages. Directus pkg & Nuxt frontend
- another branch with another pkg, which depends on SDK v13

As soon as you run `pnpm i` after changing the branch to `directus-extension`
Nuxt auto import the SDK version 13 and not the 15 anymore

Check the `.nuxt/types/import.d.ts` on `main` and after the switch
I'm unsure but do you think it's related on how Nuxt resolve auto import ? Or pnpm ?
I also thought about peerDependencies, like adding it in your package? (not sure how it works tho)

Repo:
Main branch: https://stackblitz.com/github/Vincent-HD/nuxt-directus-type-issue
Directus extension branch: https://stackblitz.com/github/Vincent-HD/nuxt-directus-type-issue/tree/directus-extension
It will install everything, open the `composables/test.ts` file and check the type of `const article = ...`

```typescript
// apps/front/.nuxt/types/imports.d.ts
// Before on main:
const readItems: typeof import('../../../../node_modules/.pnpm/@directus+sdk@15.0.1/node_modules/@directus/sdk')['readItems']
// After on directus-extension:
const readItems: typeof import('../../../../node_modules/.pnpm/@directus+sdk@13.0.2/node_modules/@directus/sdk')['readItems']
```

Do you have any ideas ?

**Comment by Vincent-HD** [comment] 2024-02-21 16:50
Updated stackblitz links

**Comment by becem-gharbi** [comment] 2024-02-22 13:57
The module uses `@directus/sdk` version 15. However as you have mentioned it uses version 13 installed by the other projects. Normally this should not happend and the modules resolution should be correct. To be honest I don't understand the reason as I'm not familiar with pnpm workspace.

The solution would be to explicitly set the resolution of `@directus/sdk` at the root of the workspace.

```json
{
  "resolutions": {
    "@directus/sdk": "^15.0.0"
  }
}
```

**Comment by Vincent-HD** [comment] 2024-02-22 15:40
Hmm, I need to try that.

But yes I feel like it's not related to your module, but rather related to Nuxt auto import resolution. Nuxt shouldn't update dependencies without even touching one file in the folder. This could be problematic, if I change a package in project A, it should'nt affect another project, without even touching any file.

I think I will open a issue on Nuxt repo, this seems very weird, I doubt this would be pnpm's fault, I think there is something wrong with the *magic* auto import from Nuxt. They're using unimport under the hood I thing to generate those files, so it could be this also.

But idk why but I have a feeling this is a specific case with **nuxt modules dependencies** and a pnpm workspace project dependencies

I'll keep you updated if you want

**Comment by becem-gharbi** [comment] 2024-02-25 07:31
I'm closing this issue for now. Please let me know with any updates on the root cause. Thanks!

**Closed as not planned by becem-gharbi** 2024-02-25 07:31 UTC
